// src/components/screens/home/top-artists/TopArtists.vue
<script setup lang="ts">
import artists from "./artists";
import ArtistsItem from "./artists-item/ArtistsItem.vue";
import styles from "./artists-item/Artists.module.scss";
import TopWrapper from "../top-wrapper/TopWrapper.vue";
</script>

<template>
  <section :class="styles.artists">
    <TopWrapper :text="'Top Artists'" />
    <ul :class="styles.artistsList">
      <ArtistsItem v-for="artist in artists" :key="artist.id" :artist="artist" />
    </ul>
  </section>
</template>

<style lang=""></style>

// src/components/screens/home/top-artists/TopArtists.tsx
import React from 'react';
import artists from './artists';
import ArtistsItem from './artists-item/ArtistsItem';
import * as styles from './artists-item/Artists.module.scss';
import TopWrapper from '../top-wrapper/TopWrapper.vue';

const TopArtists = () => {
  return (
    <section className={styles.artists}>
      <TopWrapper text={'Top Artists'} />
      <ul className={styles.artistsList}>
        {artists.map((item, index) => {
          return (
            <ArtistsItem
              key={index}
              to={item.to}
              image={item.image}
              plays={item.plays}
            >
              {item.name}
            </ArtistsItem>
          );
        })}
      </ul>
    </section>
  );
};

export default TopArtists;
