// src/components/screens/home/genre/Genre.vue
<script setup lang="ts">
import styles from "./Genre.module.scss";
import genres from "./genre-data";
import TopWrapper from "../top-wrapper/TopWrapper.vue";
import GenreItem from "./GenreItem.vue";
</script>
<template>
  <section :class="styles.genre">
    <TopWrapper :text="'Top Genre'" />
    <ul :class="styles.genreList">
      <GenreItem v-for="genre in genres" :key="genre.id" :genre="genre" />
    </ul>
  </section>
</template>

// src/components/screens/home/genre/Genre.tsx
import React from 'react';
import TopWrapper from '../top-wrapper/TopWrapper.vue';
import * as styles from './Genre.module.scss';
import genre from './genre-data';
import GenreItem from './GenreItem';

const TopGenre = () => {
  return (
    <section className={styles.genre}>
      <TopWrapper text={'Top Genre'} />
      <ul className={styles.genreList}>
        {genre.map((item, index) => {
          return (
            <GenreItem key={index} to={item.to}>
              {item.name}
            </GenreItem>
          );
        })}
      </ul>
    </section>
  );
};

export default TopGenre;
