// src/components/screens/home/right-sidebar/RightSidebar.tsx
import React, { useState } from 'react';
import TopWrapper from '../top-wrapper/TopWrapper.vue';
import * as styles from './Weekly.module.scss';
import WeeklySong from './WeeklySong';
import Player from './player/Player';
import weeklySongData from './weeklySongData';
const RightSidebar = () => {
  const [currentPlaylist, setCurrentPlaylist] = useState(weeklySongData);
  const [currentTrackIndex, setCurrentTrackIndex] = useState(0);

  const handleSongClick = (index: number) => {
    setCurrentTrackIndex(index);
  };


  return (
    <section className={styles.RightSidebar}>
      <div className={styles.WeeklyWrapper}>
        <TopWrapper text={'Top 100 Weekly'} />
        <WeeklySong playlist={currentPlaylist} onSongClick={handleSongClick} />
      </div>
      <Player
        playlist={currentPlaylist}
        currentTrackIndex={currentTrackIndex}
      />
    </section>
  );
};

export default RightSidebar;

// src/components/screens/home/right-sidebar/RightSidebar.vue
<script setup lang="ts">
import TopWrapper from "../top-wrapper/TopWrapper.vue";
import WeeklySong from "./WeeklySong.vue";
import styles from "./Weekly.module.scss";
import Player from "./player/Player.vue";
import weeklySongData from "./weeklySongData";
import { ref } from "vue";
import type { ISong } from "@/types";

const currentPlaylist = ref<ISong[]>(weeklySongData);
const currentTrackIndex = ref(0);
</script>
<template>
  <section :class="styles.RightSidebar">
    <div :class="styles.WeeklyWrapper">
      <TopWrapper text="'Top 100 Weekly'" />
      <WeeklySong
        :currentPlaylist="currentPlaylist"
        v-model:currentTrackIndex="currentTrackIndex"
      />
    </div>
    <Player :playlist="currentPlaylist" v-model:currentTrackIndex="currentTrackIndex" />
  </section>
</template>
